export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const TOTALPAGE_SUCCESS = 'TOTALPAGE_SUCCESS'
export const TOTALPAGE_FAILURE = 'TOTALPAGE_FAILURE'

export const LIST_SUCCESS = 'LIST_SUCCESS'
export const LIST_FAILURE = 'LIST_FAILURE'
export const LIST_RESIZE = 'LIST_RESIZE'
export const LIST_CACHE = 'LIST_CACHE'

export const UPDATEUI_TOGGLE = 'UPDATEUI_TOGGLE'
export const DETAILUI_TOGGLE = 'DETAILUI_TOGGLE'
